export const routes = {
    DIA_AUTH_URL: process.env.ENV_DIA_AUTH_URL,
    DIA_AUTH_EXCHANGE_REFRESH_TOKEN_URL: process.env.ENV_DIA_AUTH_REFRESHTOKENEXCHANGEURL,
    DIA_INVITATIONS_SUMMARY_URL: process.env.ENV_DIA_INVITE_SUMMARY_URL,
    DIA_USER_PROFILE_ATTRIBUTES_URL: process.env.ENV_DIA_USER_URL,
    DIA_INVITE_USER_URL: process.env.ENV_DIA_INVITE_USER_URL
}